version: '3.6'

services:
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - ./backend:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - ./backend:/var/www
    depends_on:
      - db
    container_name: project_app

  db:
    image: postgres:15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
        POSTGRES_DB: "albums"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    container_name: project_db
    